[build]
  command = "expo export -p web && cp public/auth-callback.html dist/auth-callback.html"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "dist/_expo/static/js/web"