[build]
  command = "expo export -p web && ls public && cp -v public/auth-callback.html dist/"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "dist/_expo/static/js/web"